name: Github Actions Demo
on: push
jobs:
  Example-Actions-Job:
    name: Exploring Github Actions
    # It can be windows-latest, mac-latest or instead of latest specify version.
    runs-on: ubuntu-latest
    steps: 
      # The event that triggered the workflow
      - run: echo "The job was triggered by a ${{ github.event_name }} event."

      # Runner information
      - run: echo "The job is running on a ${{ runner.os }} server hosted by Github."

      
  Second-Job:
    name: The second job running on another runner
    runs-on: ubuntu- latest
    needs: Example-Actions-Job #By default both jobs run in paralel. This specifies that the 2nd job depednds on 1st one completing.
    steps:
      - run: echo "This job is no running on ${{ runner.os }}" #If there is no space between dash and run it will be an error.
